apiVersion: v1
data:
  postgres.sh: |
    #!/bin/bash
    set -eo pipefail

    host="$(hostname -i || echo '127.0.0.1')"
    user="${POSTGRES_USER:-postgres}"
    db="${POSTGRES_DB:-$POSTGRES_USER}"
    export PGPASSWORD="${POSTGRES_PASSWORD:-}"

    args=(
    	# force postgres to not use the local unix socket (test "external" connectibility)
    	--host "$host"
    	--username "$user"
    	--dbname "$db"
    	--quiet --no-align --tuples-only
    )

    if select="$(echo 'SELECT 1' | psql "${args[@]}")" && [ "$select" = '1' ]; then
    	exit 0
    fi

    exit 1
  redis.sh: |
    #!/bin/sh
    set -eo pipefail

    host="$(hostname -i || echo '127.0.0.1')"

    if ping="$(redis-cli -h "$host" ping)" && [ "$ping" = 'PONG' ]; then
    	exit 0
    fi

    exit 1
kind: ConfigMap
metadata:
  labels:
    io.kompose.service: db
  name: db-cm1
