kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: result
  namespace: default
  annotations:
    openshift.io/host.generated: 'true'
spec:
  #host: result-default.apps-crc.testing
  path: /
  to:
    kind: Service
    name: result
    weight: 100
  port:
    targetPort: result-service
  wildcardPolicy: None
