apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: voting-route
  labels:
    app: demo-voting-app
spec:
  to:
    kind: Service
    name: voting-service
  port:
    targetPort: 8080
  tls:
    termination: edge
  wildcardPolicy: None